### ISSUE TITLE
Problem running

### ISSUE THREAD

**Issue by duhast** [sofia-netsurv/sofia-client#1]
Hi! I've cloned _master_ branch and installed yarn deps, however I'm getting the following error when trying to start:
```bash
$ yarn start
yarn run v1.17.3
$ yarn build
$ concurrently "yarn build-main" "yarn build-renderer"
$ cross-env NODE_ENV=production webpack --config ./configs/webpack.config.main.prod.babel.js --colors
$ cross-env NODE_ENV=production webpack --config ./configs/webpack.config.renderer.prod.babel.js --colors
[1] events.js:183
[1]       throw er; // Unhandled 'error' event
[1]       ^
[1] 
[1] Error: spawn webpack ENOENT
[1]     at _errnoException (util.js:1022:11)
[1]     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
[1]     at onErrorNT (internal/child_process.js:372:16)
[1]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[1]     at process._tickCallback (internal/process/next_tick.js:180:9)
[1]     at Function.Module.runMain (module.js:695:11)
[1]     at startup (bootstrap_node.js:188:16)
[1]     at bootstrap_node.js:609:3
[0] events.js:183
[0]       throw er; // Unhandled 'error' event
[0]       ^
[0] 
[0] Error: spawn webpack ENOENT
[0]     at _errnoException (util.js:1022:11)
[0]     at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
[0]     at onErrorNT (internal/child_process.js:372:16)
[0]     at _combinedTickCallback (internal/process/next_tick.js:138:11)
[0]     at process._tickCallback (internal/process/next_tick.js:180:9)
[0]     at Function.Module.runMain (module.js:695:11)
[0]     at startup (bootstrap_node.js:188:16)
[0]     at bootstrap_node.js:609:3
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[0] yarn build-main exited with code 1
[1] yarn build-renderer exited with code 1
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

What I'm doing wrong?
_P.S. I'm on Ubuntu 18.10_

**Comment by plavabe12** [comment]
Sofia Client is currently a WIP with breaking changes. Will push a release once we can confirm that it doesn't break anymore.
